Viz chapter is ready
microbiome/OMA pull request #155
Opened 2022-02-27 21:56 UTC by RiboRings

2022-02-27 22:00 UTC, antagomir commented
I suggest that @TuomasBorman checks first and I will then see after that if I have further comments.

2022-02-28 09:08 UTC, TuomasBorman requested changes
I think this is good like this already. Just some minor things that would be good to consider at least

2022-02-28 09:17 UTC, antagomir commented
Thanks! I will check the next round.

2022-03-01 15:57 UTC, RiboRings commented on 19_visualization_techniques.Rmd
> +
I wanted to give a short summary on the visual methods of the chapter on differential abundance, without repeating the examples that are already in that chapter.
Should I just delete this part?

2022-03-01 16:23 UTC, antagomir commented on 19_visualization_techniques.Rmd
> +
I would remove this. You can store it in misc.Rmd that is in the repository, but not included in the book. We can then use the text if it is useful later

2022-03-01 16:23 UTC, antagomir commented on 19_visualization_techniques.Rmd
> +For more sophisticated visualizations than those produced with `plotAbundance` and _ggplot2_, the packages _pheatmap_ and _sechm_ provide methods to include feature and sample clusters in a heat map,
"heatmap" it be

2022-03-07 07:23 UTC, TuomasBorman approved these changes
Looks good!

2022-03-07 07:23 UTC, TuomasBorman commented on 19_visualization_techniques.Rmd
> +### Heat maps
One more 'heat map'

2022-03-07 07:23 UTC, TuomasBorman commented on 19_visualization_techniques.Rmd
> +Heat maps find several other applications in biclustering and multi-assay
'Heat map'

2022-03-07 07:25 UTC, TuomasBorman commented
One more suggestion:

We have here` pheatmap` and sechm. `sechm` utilizes `complexHeatmap`. It is like better version of `pheatmap` with more options. 

`pheatmap` is valid choice for plotting matrices, however, since we introduce `sechm` (and `complexHeatmap`), should we have a small example about `complexHeatmap` + matrix? (Then user could use only `complexHeatmap`/`sechm`)

In my opinion, `complexHeatmap` is little bit more complicated but allows much more. (For example, adding text such as p-values is little bit harder than in `pheatmap`)

```
p_threshold_vis <- 0.05

# Create a heatmap and store it
plot <- Heatmap(correlations$cor, col = col_fun,
                # Print values to cells
                cell_fun = function(j, i, x, y, width, height, fill) {
                    # If the p-value is under threshold
                    if( correlations$p_adj[i, j] < p_threshold_vis )
                        # Print "X"
                        grid.text(sprintf("%s", "X"), x, y, gp = gpar(fontsize = 8, col = "black"))
                    },
                heatmap_legend_param = list(title = "", legend_height = unit(5, "cm"))
                )
```

2022-04-10 11:00 UTC, antagomir commented
@RiboRings can you resolve the conflict, and confirm that all the relevant points from the above discussion have been taken into account. Then I can confirm the merge. Thanks!

2022-04-21 07:30 UTC, antagomir commented
Same than with #134  - conflict must be resolved before we can merge this.

2022-05-04 06:54 UTC, antagomir commented
There still seems to be a build failure - we can discuss in Slack how to solve if not straightfwd. @RiboRings

2022-05-08 14:41 UTC, antagomir approved these changes

2022-05-08 14:44 UTC, antagomir commented
Still some fail checks, I am not sure from the logs what's the issue. Do you find?

2022-05-09 06:40 UTC, RiboRings commented
I'm not sure yet.

2022-05-10 07:52 UTC, antagomir commented
Ah - I think I have added this in another recent PR. Have you made sure your branch is updated from master?

2022-05-17 02:30 UTC, RiboRings commented
The error about sechm dep was solved. However, now another error appears in the logs. It is about [this chunk](https://github.com/microbiome/OMA/blob/e02dfe32589ce8eb65ea4f95c0ddee65a5d6095b/19_visualization_techniques.Rmd#L422):

```
Quitting from lines 423-436 (19_visualization_techniques.Rmd) 
Error in is.vector(features) : argument "features" is missing, with no default
```

Locally, I don't get any error. Do you have any idea what could cause this error?

2022-05-17 06:45 UTC, antagomir commented
The new version of the _sechm_ package is using argument name "features" instead of "genes". Change that on line 430 and possibly elsewhere, then it probably goes through. We had this issue also in some other Rmd files.

2022-05-17 09:05 UTC, merged