Replace subsampleCounts with rarefyAssay
microbiome/OMA pull request #462
Opened 2024-04-26 09:33 UTC by thpralas

After mia PR https://github.com/microbiome/mia/pull/536 that renamed the following function : 

- `subsampleCounts` --> `rarefyAssay`

This PR replaces `subsampleCounts` with `rarefyAssay` in the OMA book.

2024-04-26 20:00 UTC, antagomir commented
Seems good.

2024-04-26 20:05 UTC, antagomir requested changes

2024-04-26 20:05 UTC, antagomir commented on inst/pages/12_quality_control.qmd
> +[rarefyAssay](https://microbiome.github.io/mia/reference/rarefyAssay.html),
I would also add that "This remains controversial, however, and strategies to mitigate the information loss in rarefaction have been proposed [@citations]."

Add these papers in the bibtext file and cite:
https://journals.asm.org/doi/10.1128/msphere.00354-23
https://journals.asm.org/doi/10.1128/msphere.00355-23

2024-04-28 19:31 UTC, antagomir commented on inst/assets/bibliography.bib
> +    journal = {mSphere},
Put this in double curly brackets to ensure that the capitalization will be maintained in rendering to other formats. Like {{mSphere}} (this is a LaTeX trick)

2024-04-28 19:31 UTC, antagomir commented on inst/assets/bibliography.bib
> +    title = {Rarefaction is currently the best approach to control for uneven sequencing     effort in amplicon sequence analyses},
remove extra spaces

2024-04-28 19:31 UTC, antagomir commented on inst/assets/bibliography.bib
> +    url = {https://journals.asm.org/doi/abs/10.1128/msphere.00354-23}
Change this toi doi instead.

doi = {10.1128/msphere.00354-23},

2024-04-28 19:31 UTC, antagomir commented on inst/assets/bibliography.bib
> +    url = {https://journals.asm.org/doi/abs/10.1128/msphere.00355-23}
change into doi

2024-04-28 19:31 UTC, antagomir commented on inst/assets/bibliography.bib
> +    journal = {mSphere},
{{}}

2024-05-06 14:38 UTC, Daenarys8 reviewed
> LGTM

2024-05-24 10:54 UTC, TuomasBorman approved these changes

2024-05-24 11:58 UTC, merged