3D interactive plot
microbiome/OMA pull request #50
Opened 2021-07-23 13:20 UTC by ChouaibB

Hi,

Added is an example of 3D interactive plot using plotly.
Worked also when rendered to html.

2021-07-23 17:21 UTC, antagomir requested changes
- Can you add a simple link to this in beta diversity section
- No dashes in file names; replace "-" with "_"

2021-07-24 09:35 UTC, antagomir approved these changes

2021-07-24 09:36 UTC, antagomir commented
@FelixErnst this changes all dashes to underscores in file names. Just cross-checking it is ok.

2021-07-24 09:38 UTC, TuomasBorman approved these changes

2021-07-24 09:49 UTC, merged