Update 30_differential_abundance.qmd
microbiome/OMA pull request #514
Opened 2024-06-09 17:03 UTC by jkc9886

I updated this code last time but there was a clash with another PR, I incorporated those changes in mine plus the other grammatical changes.

1. the function, subsetbyPrevalent in the original code didn't work when I tried building locally. I replaced it with subsetbyPrevalentFeatures and it is working now, please cross check it.

2024-06-10 04:54 UTC, antagomir requested changes

2024-06-10 04:54 UTC, antagomir commented on inst/pages/30_differential_abundance.qmd
> +Differential Abundance Analysis (DAA) is a method used to identify differences in the abundances of individual taxa (at any taxonomic level) between two or more groups, like treatment versus control
Keep the URLs (it seems to have been removed here)

2024-06-10 04:57 UTC, antagomir commented
Thanks!

Main issues with this PR:

1) Line breaks have been changed, and as a result it is difficult to compare what exactly has changed because entire text blocks are replaced by other text blocks and sometimes the contents seems identical and sometimes not in a closer investigation -> just to keep the PR more readable, avoid changing line breaks. This does not affect the actual published layout anyway.

2) URLs have been removed in some places.

3) Large chunks of explanations with references seem to have been deleted, not immediately clear if they were just moved to other places in the document or entirely removed.


-> Make a new PR with more modest changes to start with (you can propose the same changes but in a more targeted way, like one subsection at a time to keep the PR more readable)

2024-06-11 13:34 UTC, TuomasBorman commented on inst/pages/30_differential_abundance.qmd
> +                                                                           closely related log-ratio transforms). Depending on the experimental setup, it
Something weird happening

2024-06-11 13:36 UTC, TuomasBorman commented
subsetByPrevalent is the new name in mia 1.13.21 https://microbiome.github.io/mia/reference/getPrevalence.html

2024-06-15 09:48 UTC, antagomir commented
How this is related to #508

2024-06-15 15:14 UTC, jkc9886 commented
Do you mean this PR or the discussion about the subsetbyPrevalent function?

2024-06-16 08:35 UTC, antagomir commented
There are two open PRs #508 and #514 (this one) and both of them have the same title. If they deal with different parts of the chapter then it is OK. Otherwise there is a risk of conflicts between the two PRs. Can we merge at least one of them soon.

2024-06-16 16:40 UTC, jkc9886 commented
Hello, yes we can merge this one; the only confusion was with the subsetbyPrevalent which is resolved now. Hence this PR can be merged. Could you do it @TuomasBorman ?

2024-06-17 05:50 UTC, TuomasBorman commented
Hello, I forgot, but can you first resolve the issues mentioned i this commit https://github.com/microbiome/OMA/commit/207952f25fc7283c0adb3e6141fad28865a874a6#comments

The book build is failing currently because of previous commits. That must be solved first

2024-06-17 09:02 UTC, jkc9886 commented
Hello, this commit should be closed and not merged. The PR in which I made the correct charges has already been merged earlier. Sorry for the inconvenience due to the confusion.

2024-06-25 18:09 UTC, closed without merging